### ISSUE TITLE
Asymmetric condition when peak start/end coincides with TSS

### ISSUE THREAD

**Issue by sposadac** [PatZeis/scATAC.Peak.annotation#3]
I seems to me that if a peak start or end coincides with a gene TSS the "overlap.alter.TSS" column will be populated only if the gene lies on the negative strand:
```
# case 1: peak end at TSS
TSS - peak_start > 0 --> vorzeichenS: TRUE
TSS - peak_end = 0 --> vorzeichenE:  FALSE
```
Whereas for a gene on a positive strand:
```
# case 2: peak start at TSS
TSS - peak_start = 0 --> vorzeichenS: FALSE
TSS - peak_end < 0 --> vorzeichenE:  FALSE
```

https://github.com/PatZeis/scATAC.Peak.annotation/blob/dce00b88f213a3e19a9ca81c85f133e7b0b488a2/R/scATAC.Peak.annotation.R#L371-L377

**Comment by PatZeis** [comment]
This case is evaluated if the peak is overlapping the gene body of the collapsed gene.
Then the logic for alternative TSS is, that if equations "TSS - peak _end" and "TSS - peak_start" has not the same algebraic sign, the peak is overlapping an alternative TSS. The strand is not considered.

**Comment by sposadac** [comment]
Iunderstand the strand is not directly considered, but it is implicitly considered for the TSS. That's why I refer to the strand in my artificial example. My point is that "alternative TSS" are not reported in the case 2 (see above).

**Comment by PatZeis** [comment]
thanks for this, I included the case where the distance of peak_start/peak_end to TSS = 0.

**Comment by PatZeis** [comment]
https://github.com/PatZeis/scATAC.Peak.annotation/commit/dfe04104961465d18707fea46b942de04713f2c4
